created entity class and set up persistence
in Java SE environment, javax.transaction:jta is required to avoid
java.lang.NoClassDefFoundError: javax/transaction/SystemException